//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CobranzaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gestor
    {
        public Gestor()
        {
            this.GestorXDeudas = new HashSet<GestorXDeuda>();
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public int idGestor { get; set; }
        public int idNivelGestor { get; set; }
        public int idTipoGestor { get; set; }
        public string nombres { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public System.DateTime fechaIngreso { get; set; }
        public Nullable<int> deudasRecuperadas { get; set; }
    
        public virtual ICollection<GestorXDeuda> GestorXDeudas { get; set; }
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
